version: '3.3'
services:
  hazelcast_management:
    container_name: hazelcast_management_center
    ports:
      - '8001:8080'
    image: 'hazelcast/management-center:5.2.0'
  hazelcast1:
    container_name: hazelcast1
    environment:
      - 'HZ_NETWORK_PUBLICADDRESS=192.168.1.63:5701'
    ports:
      - '5701:5701'
    image: 'hazelcast/hazelcast:5.2.1'
  hazelcast2:
    container_name: hazelcast2
    environment:
      - 'HZ_NETWORK_PUBLICADDRESS=192.168.1.63:5702'
    ports:
      - '5702:5701'
    image: 'hazelcast/hazelcast:5.2.1'
  hazelcast3:
    container_name: hazelcast3
    environment:
      - 'HZ_NETWORK_PUBLICADDRESS=192.168.1.63:5703'
    ports:
      - '5703:5701'
    image: 'hazelcast/hazelcast:5.2.1'
#  hazelcast4:
#    container_name: hazelcast4
#    environment:
#      - 'HZ_NETWORK_PUBLICADDRESS=192.168.1.63:5704'
#    ports:
#      - '5704:5701'
#    image: 'hazelcast/hazelcast:5.2.1'
#  hazelcast5:
#    container_name: hazelcast5
#    environment:
#      - 'HZ_NETWORK_PUBLICADDRESS=192.168.1.63:5705'
#    ports:
#      - '5705:5701'
#    image: 'hazelcast/hazelcast:5.2.1'